name: poc_assessor_checks_ci
# heroku authorizations:create
on:
  pull_request:
    types: [opened,reopened]
  push:

env:
  STUDENT_CODEBASE: marys_ci_cd_pipeline.yml

  # Checks
  ACTION_PI_SETUP: actions/setup-python
  RUNS_ON: ubuntu-latest

jobs:
  teacher_assessment_time:
    # if: ${{ github.ref == 'refs/heads/main' }}
    name: JOB - Devops Practitioner Assessment Bot
    runs-on: ubuntu-latest

#
#
# Start compiling report
#
#
    steps:
    - name: checkout me code
      uses: actions/checkout@v2

    - name: report header
      run: |
        echo "STUDENT_EMAIL $STUDENT_EMAIL" > grades.md
        echo "Date: $(date) " >> grades.md

    - name: check#1 is python action is used.
      run: |
        grep "${{env.ACTION_PI_SETUP}}" ${{env.STUDENT_CODEBASE}}
        if (( $? == 0 )) ; then
          echo "PI Check : PASSED" >> grades.md
        else
          echo "PI Check : FAILED" >> grades.md
        fi

    - name: check# is runner ubuntu
      run: |
        grep ${{env.RUNS_ON}} ${{env.STUDENT_CODEBASE}}
        if (( $? == 0 )) ; then
          echo "Runner Check: PASSED" >> grades.md
        else
          echo "Runner Check: FAILED" >> grades.md
        fi

    - name: archive student results
      uses: actions/upload-artifact@v2
      with:
        name: students_assessment
        path: ./grades.md
        retention-days: 5

    - name: clean up
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        rm ${{env.STUDENT_CODEBASE}}
        rm grades.md
        git config --global user.email "tonyennis@yahoo.com"
        git config --global user.name "Anthony Ennis"
        git add .
        # add commit message that matches grades
        # update call to slack to be fancy message ...
        git commit -m "deleting students submission"

  # comms_slack:
  #   needs: teacher_assessment_time
  #   name: JOB - Slack Update
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: notify-team
  #     uses: 8398a7/action-slack@v3
  #     with:
  #       status: ${{ job.status }}
  #       fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
  #     env:
  #       SLACK_WEBHOOK_URL: https://hooks.slack.com/services/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  # required
  #     if: always() # Pick up events even if the job fails or is canceled.
