name: mary_ci_pipeline
on: [push]

env:
  APP_NAME: ci-ping-pong
  GEO: eu
  PIPELINE: coding-institute-pipeline
  STUDENT_EMAIL: mary@codeinstitute.net
  STUDENT_NAME: mary j jenkins
  # heroku
  HEALTH_ENDPOINT_DEV: https://ci-ping-dev.herokuapp.com/
  HEALTH_ENDPOINT_STAGE: https://ci-ping-stage.herokuapp.com/
  HEALTH_ENDPOINT_PROD: https://ci-ping-prod.herokuapp.com/
  # GitHub Actions
  WORKFLOW_REPO: https://github.com/iot-code-institute2/devops_practitioner_assessment_bot.git
  WORKFLOW_RUN_ID: poc_assessor_checks_ci


jobs:
  # Master Only
  job1:
    name: JOB - To setup a python 3.7 enviroment
    runs-on: ubuntu-latest

    steps:
    - name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: get os version
      run: |
        uname -a >> release.md

    - name: get latest pip version
      run: |
        python -m pip install --upgrade pip
        pip -V >> release.md

    - name: get exact py version
      run: |
        python -V >> release.md
