name: poc_assessor_checks_ci
# heroku authorizations:create
on:
  pull_request:
    types: [opened,reopened]
  push:

env:
  STUDENT_CODEBASE: marys_ci_cd_pipeline.yml
  RULES_ENGINE: iot-code-institute2/rules_engline
jobs:
  teacher_assessment_time:
    # if: ${{ github.ref == 'refs/heads/main' }}
    name: JOB - Devops Practitioner Assessment Bot
    runs-on: ubuntu-latest

#
#
# Start compiling report
#
#
    steps:
    - name: checkout me code
      uses: actions/checkout@v2


    - name: report header
      run: |
        echo "**** Automated Gradid Card *****" > grades.md
        echo "Submission Date: $(date) " >> grades.md

    - name: student identifiers
      run: |
          grep STUDENT_EMAIL ${{env.STUDENT_CODEBASE}} >> grade.md
          grep STUDENT_NAME ${{env.STUDENT_CODEBASE}} >> grade.md

    - name: checkout assessment rules
      uses: actions/checkout@v2
      with:
        repository: iot-code-institute2/rules_engline
        path: rules

    - name: execute assessment rules engine
      run: |
        echo "INF: Path $(pwd)"
        ls -lrta
        echo "INF: Rules Listing"
        cat rules/rules-pr.csv

        echo "INF: Check rules..."
        IFS=","
        while read comment check expected_result
        do
          grep "$check" ${{env.STUDENT_CODEBASE}} || true
          # grep "$check" ${{env.STUDENT_CODEBASE}}
          echo "INF: RST($?)"

          if (( $? == 0 )) ; then
            echo "$comment : PASSED" >> grades.md
          else
            echo "$comment : FAILED" >> grades.md
          fi

        done < rules-pr.csv

    - name: archive student results
      uses: actions/upload-artifact@v2
      with:
        name: students_assessment
        path: ./grades.md
        retention-days: 5

    - name: clean up
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        rm ${{env.STUDENT_CODEBASE}}
        git config --global user.email "tonyennis@yahoo.com"
        git config --global user.name "Anthony Ennis"
        git add .
        cat grades.md | git commit -F -
        rm grades.md

  comms_slack:
    needs: teacher_assessment_time
    name: JOB - Slack Update
    runs-on: ubuntu-latest
    steps:
    - name: notify-team
      uses: 8398a7/action-slack@v3
      with:
        status: ${{ job.status }}
        fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
      env:
        SLACK_WEBHOOK_URL: https://hooks.slack.com/services/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  # required
      if: always() # Pick up events even if the job fails or is canceled.
