name: poc_assessor_checks_ci
# heroku authorizations:create
on:
  pull_request:
    types: [opened,reopened]
  push:

env:
  STUDENT_CODEBASE: marys_ci_cd_pipeline.yml
  RULES_ENGINE: iot-code-institute2/rules_engline

  # heroku
  HEALTH_ENDPOINT_DEV_X: https://ci-ping-dev.herokuapp.com/
  HEALTH_ENDPOINT_STAGE_X: https://ci-ping-stage.herokuapp.com/
  HEALTH_ENDPOINT_PROD_X: https://ci-ping-prod.herokuapp.com/

  # GitHub Actions
  WORKFLOW_REPO_X: https://github.com/iot-code-institute2/devops_practitioner_assessment_bot.git
  # WORKFLOW_RUN_ID_X: poc_assessor_checks_ci
  WORKFLOW_RUN_ID_X: 8759014

jobs:
  student_workflow:
    name: JOB - workflow slurper
    runs-on: ubuntu-latest

    steps:
    - name: checkout me code
      uses: actions/checkout@v2

    - name: Extract Workflow Items
      run: |
        echo "INF: My Run ID  ${{ github.run_id }}"
        wf_run_id=$(cat ${{env.STUDENT_CODEBASE}} | awk -F: '/WORKFLOW_RUN_ID/ {print $2}' | awk '{ gsub(/ /,""); print }')
        echo "INF: run_id ($wf_run_id)"
        echo "WORKFLOW_RUN_ID=$wf_run_id" >> $GITHUB_ENV

        wf_repo=$(cat ${{env.STUDENT_CODEBASE}} | awk -F: '/WORKFLOW_REPO/ {print $2":"$3}' | awk '{ gsub(/ /,""); print }')
        echo "INF: wf_repo  ($wf_repo)"
        echo "WORKFLOW_REPO=$wf_repo" >> $GITHUB_ENV

    - name: Extract Endpoints
      run: |
        hep_dev=$(gh workflow view ${{env.WORKFLOW_RUN_ID}} --yaml --repo ${{env.WORKFLOW_REPO}} | awk -F: '/HEALTH_ENDPOINT_DEV/ {print $2}')
        echo "INF: HEP#1 ($hep_dev)"
        echo "HEALTH_ENDPOINT_DEV=$hep_dev" >> $GITHUB_ENV

        hep_stage=$(gh workflow view ${{env.WORKFLOW_RUN_ID}} --yaml --repo ${{env.WORKFLOW_REPO}} | awk -F: '/HEALTH_ENDPOINT_STAGE/ {print $2}')
        echo "INF: HEP#2 ($hep_stage)"
        echo "HEALTH_ENDPOINT_STAGE=$hep_stage" >> $GITHUB_ENV

        hep_prod=$(gh workflow view ${{env.WORKFLOW_RUN_ID}} --yaml --repo ${{env.WORKFLOW_REPO}} | awk -F: '/HEALTH_ENDPOINT_PROD/ {print $2}')
        echo "INF: HEP#3 ($hep_prod)"
        echo "HEALTH_ENDPOINT_PROD=$hep_prod" >> $GITHUB_ENV



  teacher_assessment_time:
    needs: student_workflow
    # if: ${{ github.ref == 'refs/heads/main' }}
    name: JOB - Devops Practitioner Assessment Bot
    runs-on: ubuntu-latest

    steps:
    - name: checkout me code
      uses: actions/checkout@v2


    - name: report header
      run: |
        echo "**** Automated Students Grades Card *****" > grades.md
        echo "Submission Date: $(date) " >> grades.md

    - name: student identifiers
      run: |
          grep STUDENT_EMAIL ${{env.STUDENT_CODEBASE}} >> grades.md
          grep STUDENT_NAME ${{env.STUDENT_CODEBASE}} >> grades.md
          echo "---" >> grades.md

    - name: checkout assessment rules
      uses: actions/checkout@v2
      with:
        repository: iot-code-institute2/rules_engline
        path: rules

    - name: execute assessment rules engine
      env:
        CHECK_RT: ""
      run: |
        echo -e "\nINF: Path $(pwd)"
        ls -lrta
        echo -e "\nINF: Rules Listing"
        cat rules/rules-pr.csv

        echo -e "\nINF: Check rules..."
        grep --version
        echo -e "\n"

        IFS=","
        while read comment check grade expected_result
        do
          echo "Comment ($comment)"
          echo "Check ($check)"
          echo "Grade ($grade)"
          echo "Codebase under inspection (${{env.STUDENT_CODEBASE}})"

          cat ${{env.STUDENT_CODEBASE}} | grep -c "$check" && echo "Q. $comment? PASSED, Level($grade)" >> grades.md || echo "Q. $comment? FAILED, Level($grade)" >> grades.md

          # Overall Grade?

          echo -e "\n"
        done < rules/rules-pr.csv

        echo -e "\nINF: Grades Results"
        cat grades.md

    - name: workflow failure check
      run: |
        lc=$(gh run view ${{env.WORKFLOW_RUN_ID}} --repo ${{env.WORKFLOW_REPO}} --log-failed | wc -l)
        echo "INF: Line Count ($lc)"
        [[ $lc -ge 0 ]] && echo "Q. Did workflow complete without errors? PASSED, Level(PASS)" >> grades.md || echo "Q. Did workflow complete without errors? FAILED, Level(PASS)" >> grades.md

    - name: health-endpoint check - ${{env.HEALTH_ENDPOINT_DEV}}
      run: |
        echo "INF: HEP#2 (${{env.HEALTH_ENDPOINT_DEV}})"
        curl ${{env.HEALTH_ENDPOINT_DEV}}
        [[ $? -eq 0 ]] && echo "Q. Is Dev Health Endpoint Available? PASSED, Level(PASS)" >> grades.md || echo "Q. Is Dev Health Endpoint Available? FAILED, Level(PASS)" >> grades.md

    - name: health-endpoint check - ${{env.HEALTH_ENDPOINT_STAGE}}
      run: |
        echo "INF: HEP#2 (${{env.HEALTH_ENDPOINT_STAGE}})"
        curl ${{env.HEALTH_ENDPOINT_STAGE}}
        [[ $? -eq 0 ]] && echo "Q. Is Stage Health Endpoint Available? PASSED, Level(PASS)" >> grades.md || echo "Q. Is Stage Health Endpoint Available? FAILED, Level(PASS)" >> grades.md

    - name: health-endpoint check - ${{env.HEALTH_ENDPOINT_PROD}}
      run: |
        echo "INF: HEP#2 (${{env.HEALTH_ENDPOINT_PROD}})"
        curl ${{env.HEALTH_ENDPOINT_PROD}}
        [[ $? -eq 0 ]] && echo "Q. Is Prod Health Endpoint Available? PASSED, Level(PASS)" >> grades.md || echo "Q. Is Prod Health Endpoint Available? FAILED, Level(PASS)" >> grades.md


    - name: archive student results
      uses: actions/upload-artifact@v2
      with:
        name: students_assessment
        path: ./grades.md
        retention-days: 5

    - name: clean up
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        rm ${{env.STUDENT_CODEBASE}}
        git config --global user.email "tonyennis@yahoo.com"
        git config --global user.name "Anthony Ennis"
        git add .
        cat grades.md | git commit -F -
        rm grades.md

    - name: Auto-merge PRs
      run: |
        # gh pr merge --auto --merge "$PR_URL"
        echo "hi"
      env:
        PR_URL: ${{github.event.pull_request.html_url}}
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

  # comms_slack:
  #   needs: teacher_assessment_time
  #   name: JOB - Slack Update
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: notify-team
  #     uses: 8398a7/action-slack@v3
  #     with:
  #       status: ${{ job.status }}
  #       fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
  #     env:
  #       SLACK_WEBHOOK_URL: https://hooks.slack.com/services/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  # required
  #     if: always() # Pick up events even if the job fails or is canceled.
